cask "font-hack-nerd-font"

brew "ack"
brew "cask"
brew "cmake"
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "jq"
brew "luarocks"
brew "neovim", args: ["HEAD"]
brew "ninja"
brew "nvm"
brew "pygments"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "stow"
brew "the_silver_searcher"
brew "tmuxinator"
brew "wireguard-tools"
brew "zoxide"
